# fly.toml app configuration file generated for heya-from-rust-blue-wave-4090 on 2024-04-01T15:04:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heya-from-rust-blue-wave-4090'
primary_region = 'jnb'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
    dockerfile = "Dockerfile"
    ignorefile = "./dockerignore"

[env]
  FLY_SCALE_TO_ZERO = '15m'
  PORT = '8080'
  PRIMARY_REGION = 'jnb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 80
    handlers = ['http']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
    port = "8080"
    restart_limit = 6

[[vm]]
  size = 'shared-cpu-1x'
